# _k = Keys

_kGET_EXIT_ALTITUDE_INPUT = '-EXIT_ALTITUDE-'
_kGET_DROP_ZONE_LOCATION_INPUT = '-DZ_LOCATION-'
_kGET_AIRCRAFT_INPUT = '-TYPE_OF_AIRCRAFT-'
_kGET_PARACHUTE_MODEL_SIZE_INPUT = '-EQUIPMENT-'
_kGET_DATE_OF_JUMP_INPUT = '-DATE-'
_kGET_JUMP_NUMBER = '-JUMP_NO-'
_kUPDATE_JUMP_NUMBER = '-UPDATE_JUMP_NO-'
_kGET_SIGNATURE_INPUT = '-SIGNATURE-'
_kGET_DESCRIPTION_OF_JUMP = '-JUMP_DESCRIPTION-'
_kUPDATE_VIEW_LOG_BOOK_LIST = '-LOG_BOOK_LIST-'
_kGET_TABLE = '-TABLE-'

# _b = Buttons

_bLAUNCH_LOG_JUMP_WINDOW = 'Log A Jump'
_bGET_TABLE = 'Edit Selected Jump'
_bLOG_JUMP = 'Log'
_bVIEW_LOGBOOK = 'View LogBook'
_bQUIT = 'Quit'
_bBACK = 'Back'
_bEXIT = 'Exit'

# _f = Files

_fSKYDIVER_INFO_TXT = 'static/skydiver_info.txt'
_fLOGBOOK_CSV = 'static/logbook.csv'

# _d = Dictionary Keys

_dNAME = 'Name'
_dPARACHUTE_BRAND = 'Parachute Brand'
_dPARACHUTE_MODEL = 'Parachute Model'
_dPARACHUTE_SIZE = 'Parachute Size [sq. ft.]'
_dCURRENT_DROPZONE = 'Current Dropzone'
_dPRIMARY_AIRCRAFT = 'Primary Aircraft'
_dLICENSE_NUMBER = 'License Number'

# _l = Logged Jump Dictionary Keys

_lJUMP_NO = 'JUMP_NO'
_lDATE = 'DATE'
_lEXIT_ALTITUDE = 'EXIT_ALTITUDE'
_lLOCATION = 'LOCATION'
_lAIRCRAFT = 'AIRCRAFT'
_lEQUIPMENT = 'EQUIPMENT'
_lSIGNATURE = 'SIGNATURE'
_lDESCRIPTION = 'DESCRIPTION'
